 CREATE USER 'michikodb' IDENTIFIED BY 'michikodb';

 GRANT ALL PRIVILEGES ON *.* TO 'michikodb';

 create database michikodb;

 CREATE TABLE michikodb.PRAISE_WORD
(
	PRAISE_WORD_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '褒め言葉ID',
	WORD VARCHAR(100) NOT NULL COMMENT '言葉',
	PRIMARY KEY (PRAISE_WORD_ID)
) COMMENT = '褒め言葉';



